chore(deps-dev): bump the angular group in /src/main/app with 1 update (#794)
Bumps the angular group in /src/main/app with 1 update:
[@angular-devkit/build-angular](https://github.com/angular/angular-cli).

Updates `@angular-devkit/build-angular` from 17.3.1 to 17.3.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/angular/angular-cli/releases"><code>@​angular-devkit/build-angular</code>'s
releases</a>.</em></p>
<blockquote>
<h2>v17.3.2</h2>
<p><!-- raw HTML omitted --><!-- raw HTML omitted --></p>
<h1>17.3.2 (2024-03-25)</h1>
<h3><code>@​schematics/angular</code></h3>
<table>
<thead>
<tr>
<th>Commit</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/935f931eea8ddd1cb86b2275b8e384bf51e9153e"><img
src="https://img.shields.io/badge/935f931ee-fix-green" alt="fix -
935f931ee" /></a></td>
<td>rename SSR port env variable</td>
</tr>
</tbody>
</table>
<h3><code>@​angular-devkit/build-angular</code></h3>
<table>
<thead>
<tr>
<th>Commit</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/c9d4360000e6134b936781be3b0d5cf1871d44d7"><img
src="https://img.shields.io/badge/c9d436000-fix-green" alt="fix -
c9d436000" /></a></td>
<td><code>Internal server error: Invalid URL</code> when using a non
localhost IP</td>
</tr>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/59fba38ec6181c8d9c7a0636fb514c4b25aaf0cd"><img
src="https://img.shields.io/badge/59fba38ec-fix-green" alt="fix -
59fba38ec" /></a></td>
<td>ensure proper resolution of linked SCSS files</td>
</tr>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/27dd8f208911dbb2eda6d64efd6d1ce8c463ce35"><img
src="https://img.shields.io/badge/27dd8f208-fix-green" alt="fix -
27dd8f208" /></a></td>
<td>service-worker references non-existent named index output</td>
</tr>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/c12907d92f8a2268541fd3bf28857dbb216ec7c9"><img
src="https://img.shields.io/badge/c12907d92-fix-green" alt="fix -
c12907d92" /></a></td>
<td>update <code>webpack-dev-middleware</code> to
<code>6.1.2</code></td>
</tr>
</tbody>
</table>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/angular/angular-cli/blob/main/CHANGELOG.md"><code>@​angular-devkit/build-angular</code>'s
changelog</a>.</em></p>
<blockquote>
<h1>17.3.2 (2024-03-25)</h1>
<h3><code>@​schematics/angular</code></h3>
<table>
<thead>
<tr>
<th>Commit</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/935f931eea8ddd1cb86b2275b8e384bf51e9153e">935f931ee</a></td>
<td>fix</td>
<td>rename SSR port env variable</td>
</tr>
</tbody>
</table>
<h3><code>@​angular-devkit/build-angular</code></h3>
<table>
<thead>
<tr>
<th>Commit</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/c9d4360000e6134b936781be3b0d5cf1871d44d7">c9d436000</a></td>
<td>fix</td>
<td><code>Internal server error: Invalid URL</code> when using a non
localhost IP</td>
</tr>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/59fba38ec6181c8d9c7a0636fb514c4b25aaf0cd">59fba38ec</a></td>
<td>fix</td>
<td>ensure proper resolution of linked SCSS files</td>
</tr>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/27dd8f208911dbb2eda6d64efd6d1ce8c463ce35">27dd8f208</a></td>
<td>fix</td>
<td>service-worker references non-existent named index output</td>
</tr>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/c12907d92f8a2268541fd3bf28857dbb216ec7c9">c12907d92</a></td>
<td>fix</td>
<td>update <code>webpack-dev-middleware</code> to
<code>6.1.2</code></td>
</tr>
</tbody>
</table>
<!-- raw HTML omitted -->
<p><!-- raw HTML omitted --><!-- raw HTML omitted --></p>
<h1>16.2.13 (2024-03-25)</h1>
<h3><code>@​angular-devkit/build-angular</code></h3>
<table>
<thead>
<tr>
<th>Commit</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/5ad507e3d4cb27fb275d255018b9b6e735835711">5ad507e3d</a></td>
<td>fix</td>
<td><code>update webpack-dev-middleware</code> to
<code>6.1.2</code></td>
</tr>
</tbody>
</table>
<!-- raw HTML omitted -->
<p><!-- raw HTML omitted --><!-- raw HTML omitted --></p>
<h1>15.2.11 (2024-03-25)</h1>
<h3><code>@​angular-devkit/build-angular</code></h3>
<table>
<thead>
<tr>
<th>Commit</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><a
href="https://github.com/angular/angular-cli/commit/c6feb0bb0247a1cf17e17325b8c42d0d6a7d1451">c6feb0bb0</a></td>
<td>fix</td>
<td><code>update webpack-dev-middleware</code> to
<code>6.1.2</code></td>
</tr>
</tbody>
</table>
<!-- raw HTML omitted -->
<p><!-- raw HTML omitted --><!-- raw HTML omitted --></p>
<h1>18.0.0-next.0 (2024-03-21)</h1>
<h2>Breaking Changes</h2>
<h3><code>@​angular/cli</code></h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/angular/angular-cli/commit/8a6550dcc8dba007901afcc39b900a43c59397d3"><code>8a6550d</code></a>
release: cut the v17.3.2 release</li>
<li><a
href="https://github.com/angular/angular-cli/commit/59fba38ec6181c8d9c7a0636fb514c4b25aaf0cd"><code>59fba38</code></a>
fix(<code>@​angular-devkit/build-angular</code>): ensure proper
resolution of linked SCSS f...</li>
<li><a
href="https://github.com/angular/angular-cli/commit/27dd8f208911dbb2eda6d64efd6d1ce8c463ce35"><code>27dd8f2</code></a>
fix(<code>@​angular-devkit/build-angular</code>): service-worker
references non-existent na...</li>
<li><a
href="https://github.com/angular/angular-cli/commit/935f931eea8ddd1cb86b2275b8e384bf51e9153e"><code>935f931</code></a>
fix(<code>@​schematics/angular</code>): rename SSR port env
variable</li>
<li><a
href="https://github.com/angular/angular-cli/commit/c12907d92f8a2268541fd3bf28857dbb216ec7c9"><code>c12907d</code></a>
fix(<code>@​angular-devkit/build-angular</code>): update
<code>webpack-dev-middleware</code> to <code>6.1.2</code></li>
<li><a
href="https://github.com/angular/angular-cli/commit/c9d4360000e6134b936781be3b0d5cf1871d44d7"><code>c9d4360</code></a>
fix(<code>@​angular-devkit/build-angular</code>): <code>Internal server
error: Invalid URL</code> when...</li>
<li><a
href="https://github.com/angular/angular-cli/commit/1a3257aac6d83c54d712d458d537222d2f6db8b6"><code>1a3257a</code></a>
refactor(<code>@​schematics/angular</code>): Use MaybeAsync and
GuardResult types to reduce...</li>
<li>See full diff in <a
href="https://github.com/angular/angular-cli/compare/17.3.1...17.3.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@angular-devkit/build-angular&package-manager=npm_and_yarn&previous-version=17.3.1&new-version=17.3.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>